/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202457201065;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sitin
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        Dasbord.setBackground(new Color(0, 134, 179));
        pConten.removeAll();
        pConten.add(new panelDasbor());
        pConten.repaint();
        pConten.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dasbord = new javax.swing.JPanel();
        pConten = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jJurusan = new javax.swing.JButton();
        jGuru = new javax.swing.JButton();
        jKelas = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jAbout = new javax.swing.JButton();
        jSiswa = new javax.swing.JButton();
        jDasbor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Dasbord.setMaximumSize(new java.awt.Dimension(1023, 700));

        pConten.setPreferredSize(new java.awt.Dimension(780, 1555));
        pConten.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout DasbordLayout = new javax.swing.GroupLayout(Dasbord);
        Dasbord.setLayout(DasbordLayout);
        DasbordLayout.setHorizontalGroup(
            DasbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DasbordLayout.createSequentialGroup()
                .addComponent(pConten, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DasbordLayout.setVerticalGroup(
            DasbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConten, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jJurusan.setBackground(new java.awt.Color(102, 153, 255));
        jJurusan.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jJurusan.setForeground(new java.awt.Color(255, 255, 255));
        jJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-school-20.png"))); // NOI18N
        jJurusan.setText("Jurusan");
        jJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJurusanActionPerformed(evt);
            }
        });

        jGuru.setBackground(new java.awt.Color(102, 153, 255));
        jGuru.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jGuru.setForeground(new java.awt.Color(255, 255, 255));
        jGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-teacher-20.png"))); // NOI18N
        jGuru.setText("Guru");
        jGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuruActionPerformed(evt);
            }
        });

        jKelas.setBackground(new java.awt.Color(102, 153, 255));
        jKelas.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jKelas.setForeground(new java.awt.Color(255, 255, 255));
        jKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-class-20.png"))); // NOI18N
        jKelas.setText("Kelas");
        jKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKelasActionPerformed(evt);
            }
        });

        jLogout.setBackground(new java.awt.Color(102, 153, 255));
        jLogout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-logout-20.png"))); // NOI18N
        jLogout.setText("Logout");
        jLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        jAbout.setBackground(new java.awt.Color(102, 153, 255));
        jAbout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jAbout.setForeground(new java.awt.Color(255, 255, 255));
        jAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-about-20.png"))); // NOI18N
        jAbout.setText("About");
        jAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutActionPerformed(evt);
            }
        });

        jSiswa.setBackground(new java.awt.Color(102, 153, 255));
        jSiswa.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jSiswa.setForeground(new java.awt.Color(255, 255, 255));
        jSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-student-20.png"))); // NOI18N
        jSiswa.setText("Siswa");
        jSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSiswaActionPerformed(evt);
            }
        });

        jDasbor.setBackground(new java.awt.Color(102, 153, 255));
        jDasbor.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jDasbor.setForeground(new java.awt.Color(255, 255, 255));
        jDasbor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-dashboard-20.png"))); // NOI18N
        jDasbor.setText("Dashboard");
        jDasbor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jDasbor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jDasbor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDasborActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-student-36.png"))); // NOI18N
        jLabel1.setText("ALOOMNI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDasbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDasbor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogout)
                .addContainerGap(739, Short.MAX_VALUE))
        );

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202457201065/gambar/icons8-exit-48.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dasbord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dasbord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJurusanActionPerformed
        // TODO add your handling code here:
        pConten.removeAll();
        pConten.add(new panelJurusan());
        pConten.repaint();
        pConten.revalidate();
    }//GEN-LAST:event_jJurusanActionPerformed

    private void jGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuruActionPerformed
        // TODO add your handling code here:
        pConten.removeAll();
        pConten.add(new PanelGuru());
        pConten.repaint();
        pConten.revalidate();   
    }//GEN-LAST:event_jGuruActionPerformed

    private void jKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKelasActionPerformed
        // TODO add your handling code here:
        pConten.removeAll();
        pConten.add(new panelKelas());
        pConten.repaint();
        pConten.revalidate();  
    }//GEN-LAST:event_jKelasActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
 int pilihan =  JOptionPane.showConfirmDialog(null, 
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            System.out.println("Keluar dari aplikasi...");
            System.exit(0);
        } else {
            System.out.println("Aksi dibatalkan.");
        } 
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jDasborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDasborActionPerformed
        // TODO add your handling code here:
        pConten.removeAll();
        pConten.add(new panelDasbor());
        pConten.repaint();
        pConten.revalidate();      
    }//GEN-LAST:event_jDasborActionPerformed

    private void jSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSiswaActionPerformed
        // TODO add your handling code here:
       pConten.removeAll();
       pConten.add(new panelSiswa());
       pConten.repaint();
       pConten.revalidate();
    }//GEN-LAST:event_jSiswaActionPerformed

    private void jAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutActionPerformed
        // TODO add your handling code here:
        pConten.removeAll();
        pConten.add(new panelAbout());
        pConten.repaint();
        pConten.revalidate();  
    }//GEN-LAST:event_jAboutActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dasbord;
    private javax.swing.JButton jAbout;
    private javax.swing.JButton jDasbor;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jGuru;
    private javax.swing.JButton jJurusan;
    private javax.swing.JButton jKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSiswa;
    private javax.swing.JPanel pConten;
    // End of variables declaration//GEN-END:variables
}
