/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package alumni202457201065;

import java.awt.event.ActionEvent;


/**
 *
 * @author sitin
 */
public class panelSiswa extends javax.swing.JPanel {

    /** Creates new form panelSiswa */
    public panelSiswa() {
        initComponents();
jFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jFoto.setPreferredSize(new java.awt.Dimension(120, 160));

jPilihFoto.setText("Pilih Foto");
jPilihFoto.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jPilihFotoActionPerformed(evt);
    
}

        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNis = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tTglLhr = new javax.swing.JTextField();
        tTl = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tHp = new javax.swing.JTextField();
        CbJk = new javax.swing.JComboBox<>();
        CbKls = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jFoto = new javax.swing.JLabel();
        jPilihFoto = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Siswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(1177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 32, 1262, 37);
        add(tNis);
        tNis.setBounds(288, 151, 282, 30);
        add(tNama);
        tNama.setBounds(288, 210, 282, 30);
        add(tTglLhr);
        tTglLhr.setBounds(288, 405, 282, 30);
        add(tTl);
        tTl.setBounds(288, 341, 282, 30);
        add(tAlamat);
        tAlamat.setBounds(656, 280, 269, 161);
        add(tHp);
        tHp.setBounds(656, 151, 269, 30);

        CbJk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(CbJk);
        CbJk.setBounds(288, 269, 282, 39);

        CbKls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(CbKls);
        CbKls.setBounds(656, 210, 269, 30);

        jLabel3.setText("NIS");
        add(jLabel3);
        jLabel3.setBounds(288, 129, 18, 16);

        jLabel4.setText("Nama");
        add(jLabel4);
        jLabel4.setBounds(288, 193, 32, 16);

        jLabel5.setText("Jenis Kelamin");
        add(jLabel5);
        jLabel5.setBounds(288, 247, 71, 16);

        jLabel6.setText("Tempat Lahir");
        add(jLabel6);
        jLabel6.setBounds(288, 319, 70, 16);

        jLabel7.setText("Tanggal Lahir");
        add(jLabel7);
        jLabel7.setBounds(288, 383, 72, 16);

        jLabel8.setText("Hp");
        add(jLabel8);
        jLabel8.setBounds(656, 129, 16, 16);

        jLabel9.setText("Kelas");
        add(jLabel9);
        jLabel9.setBounds(656, 193, 27, 16);

        jLabel10.setText("Alamat");
        add(jLabel10);
        jLabel10.setBounds(656, 258, 38, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(74, 642, 851, 309);

        bTambah.setBackground(new java.awt.Color(0, 204, 102));
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        add(bTambah);
        bTambah.setBounds(74, 538, 93, 35);

        bUbah.setBackground(new java.awt.Color(255, 204, 51));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        add(bUbah);
        bUbah.setBounds(194, 538, 93, 35);

        bHapus.setBackground(new java.awt.Color(255, 51, 51));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        add(bHapus);
        bHapus.setBounds(314, 538, 93, 35);

        bReset.setBackground(new java.awt.Color(51, 153, 235));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        add(bReset);
        bReset.setBounds(433, 538, 93, 35);

        jFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFoto.setText("Foto");
        jFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jFoto);
        jFoto.setBounds(84, 154, 168, 241);

        jPilihFoto.setBackground(new java.awt.Color(102, 153, 255));
        jPilihFoto.setText("Pilih Foto");
        jPilihFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPilihFotoActionPerformed(evt);
            }
        });
        add(jPilihFoto);
        jPilihFoto.setBounds(110, 410, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed

    private void jPilihFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPilihFotoActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Pilih Foto");
    fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);

    // Filter hanya file gambar
    javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter(
        "Gambar", "jpg", "jpeg", "png", "bmp"
    );
    fileChooser.setFileFilter(filter);

    int hasil = fileChooser.showOpenDialog(this);
    if (hasil == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileGambar = fileChooser.getSelectedFile();
        try {
            // Baca dan ubah ukuran gambar
            java.awt.Image img = javax.imageio.ImageIO.read(fileGambar).getScaledInstance(
                jFoto.getWidth(), jFoto.getHeight(), java.awt.Image.SCALE_SMOOTH
            );
            jFoto.setIcon(new javax.swing.ImageIcon(img));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka gambar: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jPilihFotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbJk;
    private javax.swing.JComboBox<String> CbKls;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPilihFoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tHp;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNis;
    private javax.swing.JTextField tTglLhr;
    private javax.swing.JTextField tTl;
    // End of variables declaration//GEN-END:variables

}
