/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202457201065;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sitin
 */
public class panelKelas extends javax.swing.JPanel {
     DefaultTableModel model;
    int rowSelected = -1;


    /**
     * Creates new form panelKelas
     */
    public panelKelas() {
        initComponents();
        model = new DefaultTableModel(new String[]{"Kode Kelas", "Nama kelas", "Tingkatan", "Jurusan", "Wali kelas"}, 0);
jTable1.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jKodeKelas = new javax.swing.JTextField();
        jNamakKls = new javax.swing.JTextField();
        CbJrsn = new javax.swing.JComboBox<>();
        CbTingktn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jWaliKls = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jLpanel = new javax.swing.JLayeredPane();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Kelas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(1078, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 44, 1160, 32);

        jKodeKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKodeKelasActionPerformed(evt);
            }
        });
        add(jKodeKelas);
        jKodeKelas.setBounds(54, 150, 179, 50);

        jNamakKls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamakKlsActionPerformed(evt);
            }
        });
        add(jNamakKls);
        jNamakKls.setBounds(54, 231, 179, 50);

        CbJrsn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPA ", "IPS", "AGAMA" }));
        add(CbJrsn);
        CbJrsn.setBounds(54, 396, 179, 55);

        CbTingktn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        add(CbTingktn);
        CbTingktn.setBounds(54, 312, 179, 55);

        jLabel2.setText("Kode Kelas");
        add(jLabel2);
        jLabel2.setBounds(54, 128, 57, 16);

        jLabel3.setText("Nama Kelas");
        add(jLabel3);
        jLabel3.setBounds(54, 212, 62, 16);

        jLabel4.setText("Tingkatan");
        add(jLabel4);
        jLabel4.setBounds(54, 293, 53, 16);

        jLabel5.setText("Jurusan");
        add(jLabel5);
        jLabel5.setBounds(54, 379, 40, 16);

        jLabel6.setText("Wali Kelas");
        add(jLabel6);
        jLabel6.setBounds(54, 463, 53, 16);
        add(jWaliKls);
        jWaliKls.setBounds(54, 491, 179, 52);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(292, 150, 529, 402);

        bTambah.setBackground(new java.awt.Color(0, 204, 102));
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        add(bTambah);
        bTambah.setBounds(292, 604, 93, 37);

        bUbah.setBackground(new java.awt.Color(255, 204, 51));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        add(bUbah);
        bUbah.setBounds(403, 604, 93, 37);

        bHapus.setBackground(new java.awt.Color(255, 51, 51));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        add(bHapus);
        bHapus.setBounds(514, 604, 93, 37);

        bReset.setBackground(new java.awt.Color(51, 153, 252));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        add(bReset);
        bReset.setBounds(625, 604, 93, 37);

        javax.swing.GroupLayout jLpanelLayout = new javax.swing.GroupLayout(jLpanel);
        jLpanel.setLayout(jLpanelLayout);
        jLpanelLayout.setHorizontalGroup(
            jLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jLpanelLayout.setVerticalGroup(
            jLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        add(jLpanel);
        jLpanel.setBounds(-360, 0, 1190, 1270);
    }// </editor-fold>//GEN-END:initComponents

    private void jKodeKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKodeKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKodeKelasActionPerformed

    private void jNamakKlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamakKlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamakKlsActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        String KK = jKodeKelas.getText();
        String namaKls = jNamakKls.getText();
        String Wk = jWaliKls.getText();
        String jrsn = CbJrsn.getSelectedItem().toString();
        String tngktn = CbTingktn.getSelectedItem().toString();

        model.setValueAt(KK, selectedRow, 0);
        model.setValueAt(namaKls, selectedRow, 1);
        model.setValueAt(tngktn, selectedRow, 3);
        model.setValueAt(jrsn, selectedRow, 3);
        model.setValueAt(Wk, selectedRow, 2);
        resetForm();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diubah.");
    }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
       String KK = jKodeKelas.getText();
        String namaKls = jNamakKls.getText();
        String Wk = jWaliKls.getText();
        String jrsn = CbJrsn.getSelectedItem().toString();
        String tngktn = CbTingktn.getSelectedItem().toString(); 

    if (KK.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
    if(namaKls.isEmpty()){
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
    }
    if(tngktn.isEmpty()){
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
    }
    if(jrsn.isEmpty()){
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
    }
    if(Wk.isEmpty()){
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
    }
    } else {
        model.addRow(new Object[]{KK, namaKls, jrsn, tngktn, Wk});
        resetForm();
    }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        model.removeRow(selectedRow);
        resetForm();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus.");
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbJrsn;
    private javax.swing.JComboBox<String> CbTingktn;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JTextField jKodeKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLpanel;
    private javax.swing.JTextField jNamakKls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jWaliKls;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
       jKodeKelas.setText("");
    jNamakKls.setText("");
    jTable1.clearSelection(); 
    CbTingktn.setSelectedIndex(0);
    CbJrsn.setSelectedIndex(0); 
    jWaliKls.setText("");  
    }
}
